name: CI
on:
  push:
    branches:
      - "main"
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'

jobs:
  lint-and-check:
    name: Lint & Type Check
    runs-on: ubuntu-latest
    if: ${{ !startsWith(github.event.head_commit.message, 'wip:') }}
    permissions:
      checks: write
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Setup Nodejs environment
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: "yarn"
      - name: Install Dependencies
        run: yarn --frozen-lockfile
      - name: Lint Client
        run: yarn client:esl --output-file eslint_report.client.json --format json
        continue-on-error: true
      - name: Type Check Client
        run: yarn client:tsc > typescript.client.log
        continue-on-error: true
      - name: Lint Server
        run: yarn server:esl --output-file eslint_report.server.json --format json
        continue-on-error: true
      - name: Type Check Server
        run: yarn server:tsc > typescript.server.log
        continue-on-error: true
      - name: Annotate Code
        uses: DerLev/eslint-annotations@v1
        with:
          eslint-report: eslint_report.client.json eslint_report.server.json
          typescript-log: typescript.client.log typescript.server.log
          github-token: ${{ secrets.GITHUB_TOKEN }}
          error-on-warn: true
          status-check-name: Annotations
          fail-in-pr: false
